language: node_js
script:
- ls
deploy:
  provider: s3
  access_key_id: AKIAI3WMB2DKHPVNU4NA
  bucket: games.randomchaos.com
  secret_access_key:
    secure: HdT0yo1FFsL4jv8T8s3V+EdVfr/qIjVPN4OCNVxuiRGWq9v/fbQeddyEqdJTA47vp8IxMv0bAw+VUC9zMs8xkDgfrFdSsiBO/lnBdC59IUwS2PfEj/jM+Yxl3A3Tdy+5+4f0p1TTdHzwBVSeofPwJKdWxxk2tFlZY4wPr44uJZqjIxeJ+qvQiTz/5bOuVmx+nCCiBenNPH8RTctwAr01+ooMd3QBa4tv9ceAgjWa6N2QoEYdMTGpDBOkoNY+H6LU8lP/jgZSttsouGsanx4e48mmYXuLU2HgSb5Tdkzlji2XcXRziQngmk9xUMBXdms/bejQ27/W5PS68mDjth0jhViOxWkCsi3yzMv2+4BFz9Hzf6SQp79tkHRYvpZQMjLT00FRtiNKvpBYZZQIIed4nAtfBurKKV/0L0hrDN8VexPrNpcUC4dxZR6VcFDf9cYPHNWfbsFtj+TU896laJpLhoWeTxaWilSJdrQg9ZZX1rY63qCH8degi0GdzkAFAAfbGx4TyKlPv+3apyeIH7mJQaoN/B7ea2rP+T+oWoQ7ebX4Jheka3PvtGYRSf0R9BacZ7eE/vEUJ3OSVmLT36LbGmTexqJz71y3J8Yt3q/Ayporc7VSTKLja8JQYtmouM8QHMafrLJUx6AtNEen6JY7d5bGhaUtCuy8RZtsc2g20gY=
  acl: public_read
  local_dir: build
  skip_cleanup: true
